---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
base_path="C:/Users/koki2/Desktop/DS/ML_Competition/NCAA_2022_W"
sample_sub <- read_csv(file.path(base_path, "data", "WSampleSubmissionStage1.csv"), col_types = cols(.default = "c"))
train_df <- sample_sub %>% 
  separate(ID, sep = "_", into = c("Season", "teamId_01", "teamId_02"))
```


```{r}
WTeams <- read_csv(file.path(base_path, "data", "WTeams.csv"), col_types = cols(.default = "c"))
WNCAATourneyCompactResults <- read_csv(file.path(base_path, "data", "WNCAATourneyCompactResults.csv"), col_types = cols(.default = "c"))
WRegularSeasonCompactResults <- read_csv(file.path(base_path, "data", "WRegularSeasonCompactResults.csv"), col_types = cols(.default = "c"))
```

```{r}
WNCAATourneyCompactResults_01 <- WNCAATourneyCompactResults %>% 
  mutate(WTeamID = as.numeric(WTeamID),
         LTeamID = as.numeric(LTeamID),
         teamID_01 = ifelse(WTeamID < LTeamID, WTeamID, LTeamID),
         teamID_02 = ifelse(WTeamID > LTeamID, WTeamID, LTeamID),
         target = ifelse(teamID_01 == WTeamID, 1, 0),
         type = "WNCAATourneyCompactResults") %>% 
  select(Season, teamID_01, teamID_02, target, type)
WRegularSeasonCompactResults_01 <- WRegularSeasonCompactResults %>% 
  mutate(WTeamID = as.numeric(WTeamID),
         LTeamID = as.numeric(LTeamID),
         teamID_01 = ifelse(WTeamID < LTeamID, WTeamID, LTeamID),
         teamID_02 = ifelse(WTeamID > LTeamID, WTeamID, LTeamID),
         target = ifelse(teamID_01 == WTeamID, 1, 0),
         type = "WRegularSeasonCompactResults") %>% 
  select(Season, teamID_01, teamID_02, target, type)

compact_result <- WNCAATourneyCompactResults_01 %>% 
  bind_rows(WRegularSeasonCompactResults_01) %>% 
  mutate(teamID_01 = as.character(teamID_01),
         teamID_02 = as.character(teamID_02)) %>% 
  unique()
compact_result_01 <- compact_result %>% 
  group_by(Season, teamID_01, teamID_02) %>% 
  summarise(target = mean(target),
            .groups = "drop")
```



```{r}
WRegularSeasonCompactResults <- read_csv(file.path(base_path, "data", "WRegularSeasonCompactResults.csv"), col_types = cols(.default = "c"))
WRegularSeasonDetailedResults <- read_csv(file.path(base_path, "data", "WRegularSeasonDetailedResults.csv"), col_types = cols(.default = "c"))
WNCAATourneyCompactResults <- read_csv(file.path(base_path, "data", "WNCAATourneyCompactResults.csv"), col_types = cols(.default = "c"))
```


```{r}
compact <- WRegularSeasonCompactResults %>% 
  bind_rows(WRegularSeasonDetailedResults) %>% 
  group_by(Season, WTeamID, LTeamID) %>% 
  summarise(n = n(), .groups = "drop") %>% 
  mutate(WTeamID = as.numeric(WTeamID),
         LTeamID = as.numeric(LTeamID),
         teamID_01 = ifelse(WTeamID < LTeamID, WTeamID, LTeamID),
         teamID_02 = ifelse(WTeamID > LTeamID, WTeamID, LTeamID),
         target = ifelse(teamID_01 == WTeamID, 1, 0)) %>% 
  group_by(Season, teamID_01, teamID_02) %>% 
  summarise(target = mean(target),
            .groups = "drop") %>% 
  mutate(teamID_01 = as.character(teamID_01),
         teamID_02 = as.character(teamID_02))
```





```{r}
test_df <- train_df %>% 
  left_join(WTeams, by = c("teamId_01"="TeamID")) %>% 
  left_join(WTeams, by = c("teamId_02"="TeamID")) %>% 
  left_join(compact_result_01, by = c("Season"="Season",
                                   "teamId_01"="teamID_01",
                                   "teamId_02"="teamID_02")) %>% 
  filter(!is.na(target))
names(test_df) <- names(test_df) %>% 
  str_replace_all("\\.x", "_01") %>% 
  str_replace_all("\\.y", "_02")

write_csv(test_df, file.path(base_path, "data", "train_df.csv"))
```

